# Generated by Django 5.2.7 on 2025-10-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='Subnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(help_text='Например, 217.116.51.0/24', max_length=32, unique=True)),
                ('network_name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=255, unique=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('online', models.BooleanField(default=False)),
                ('ips', models.ManyToManyField(related_name='domains', to='network.ipaddress')),
            ],
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='subnet',
            field=models.ManyToManyField(related_name='ips', to='network.subnet'),
        ),
    ]
