# Generated by Django 5.2.7 on 2025-11-16 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=45, unique=True)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('cidr', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['address'],
            },
        ),
        migrations.CreateModel(
            name='ScanSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_domain', models.CharField(db_index=True, max_length=255)),
                ('depth', models.PositiveIntegerField(default=3)),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('running', 'Выполняется'), ('completed', 'Завершено'), ('failed', 'Ошибка')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(choices=[('dns', 'DNS A Record'), ('tls', 'TLS Certificate'), ('reverse_dns', 'Reverse DNS')], default='dns', max_length=50)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_links', to='network.domain')),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_links', to='network.ipaddress')),
                ('scan_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='network.scansession')),
            ],
            options={
                'ordering': ['-discovered_at'],
                'unique_together': {('scan_session', 'domain', 'ip')},
            },
        ),
    ]
