# Generated by Django 5.2.7 on 2025-10-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
